source 'https://rubygems.org'
gem 'selenium-webdriver'
gem 'cucumber'
gem 'page-object'
gem 'rspec'
gem 'capybara'
gem 'rake'
gem 'chromedriver-helper'
gem 'pry'
gem 'faker'
gem 'poltergeist'
gem 'ffi', '1.9.24'
gem 'site_prism'
gem 'syntax'
gem 'rubocop'
gem 'without_accents'
gem 'os'
gem 'xml-to-json'
gem 'documentos_br'
gem 'nokogiri'
gem 'rubysl-ostruct', '~> 2.1'
gem 'intellisense-ruby', '~> 0.7.8'
gem 'calabash-android'