url: 'http://www.yaman.com.br/'


servicos_cep:
    urlCorreiosCepRest: 'http://correiosapi.apphb.com/cep/'
    urlCorreiosCepSoap: 'http://ws.correios.com.br/calculador/CalcPrecoPrazo.asmx'
    
soapAction:
    calcPrazo: 'http://tempuri.org/CalcPrazo'
    calcPrecoPrazo: 'http://tempuri.org/CalcPrecoPrazo'
    calcPreco: 'http://tempuri.org/CalcPreco'

cep:
    valido: '06220090'
    destinoValido: '06415130'
    invalido: '99999999'
    
pesquisa:
    nome: Gabriel Aguido Fraga